//login do usuario
POST  http://localhost:3333/auth/login
Content-Type: application/json

{
    "email": "max@tim9.com",
    "password": "testando1234"
}
###

// Registrar novo usuario
POST http://localhost:3333/auth/register
Content-Type: application/json

{
    "name": "pedrinho",
    "email": "max@tim11.com",
    "password": "testando1234"
}  
###

// checar token
POST  http://localhost:3333/auth/me
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJuYW1lIjoibWF4NyIsImVtYWlsIjoibWF4QHRpbTkuY29tIiwiaWF0IjoxNjg5Nzg0MzIxLCJleHAiOjE2ODk3ODc5MjEsImlzcyI6ImxvZ2luIn0.P4IKSF5gytYH0CcsXIdDW1QZgS3ppkRAbfSVEXv4OJc
###




