//login do usuario
POST  http://localhost:3333/auth/login
Content-Type: application/json

{
    "email": "max@teste.com",
    "password": "123456"
}
###

// Registrar novo usuario
POST http://localhost:3333/auth/register
Content-Type: application/json

{
    "name": "max",
    "email": "max@teste.com",
    "password": "123456"
}  
###

// checar token
POST  http://localhost:3333/auth/me
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJuYW1lIjoibWF4IiwiZW1haWwiOiJtYXhAdGltMTIuY29tIiwiaWF0IjoxNjkxMTc5MjExLCJleHAiOjE2OTE3ODQwMTEsImlzcyI6ImxvZ2luIn0.5TZykZFkp5JeLr7REopXsAaWGU5ruv-yA6zjHsauaEg
###




