//criando post
POST http://localhost:3333/posts/create
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJuYW1lIjoibWF4IiwiZW1haWwiOiJtYXhAdGltMTIuY29tIiwiaWF0IjoxNjkwODM3OTIwLCJleHAiOjE2OTE0NDI3MjAsImlzcyI6ImxvZ2luIn0.Uk6Ui7wU3W5DQoyzBYmPt4SUO0hvM2cyGzNN2H9-r8M

{
   "title" : "para funcionar2",
   "content" : "green",
   "color": "#9CD483",
   "deleted": true
}
###

// Pegando todas as postagens de um usuario
GET http://localhost:3333/posts
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJuYW1lIjoibWF4IiwiZW1haWwiOiJtYXhAdGltMTIuY29tIiwiaWF0IjoxNjkwNjM4MzIwLCJleHAiOjE2OTEyNDMxMjAsImlzcyI6ImxvZ2luIn0.YEXbrIhYhget1AYAPI7LMvxi6H5ma7I-lAyzSvRU_0w
###

//Pegando postagem especifica
GET http://localhost:3333/posts/508
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJuYW1lIjoibWF4IiwiZW1haWwiOiJtYXhAdGltMTIuY29tIiwiaWF0IjoxNjkwNjM4MzIwLCJleHAiOjE2OTEyNDMxMjAsImlzcyI6ImxvZ2luIn0.YEXbrIhYhget1AYAPI7LMvxi6H5ma7I-lAyzSvRU_0w
###

//Buscando postagem por palavra
POST  http://localhost:3333/posts/testando   
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJuYW1lIjoibWF4IiwiZW1haWwiOiJtYXhAdGltMTIuY29tIiwiaWF0IjoxNjkwNjM4MzIwLCJleHAiOjE2OTEyNDMxMjAsImlzcyI6ImxvZ2luIn0.YEXbrIhYhget1AYAPI7LMvxi6H5ma7I-lAyzSvRU_0w
Content-Type: application/json

###


///Alterando post
PATCH http://localhost:3333/posts/115
Content-Type: application/json

{
   "title" : "alterando",
   "content" : "alterou"
}
###

//Movendo para a lixeira 
PATCH http://localhost:3333/posts/trash/815
###


// deletando post
DELETE http://localhost:3333/posts/210
###

